/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
 package Vista;

 //17/03/2026 Codigo Ya Estructurado. Por errores de clases conjuntas a otros grupos
 //no se puede probar si el funcionamiento es correcto. Esperando a solución de errores de clases. 
 
import Modelo.AsignacionPerfilUsuarioDAO;
import Controlador.AsignacionPerfilUsuario;
import java.util.List;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jennifer Barrios 9959-24-10016
 */
public class MantenimientoAsignacionPerfilUsuario extends javax.swing.JFrame {

    AsignacionPerfilUsuarioDAO dao = new AsignacionPerfilUsuarioDAO();
    
    /**
     * Creates new form MantenimientoAsignacion
     */
    public MantenimientoAsignacionPerfilUsuario() {
        initComponents();
        llenarTabla();
        cargarCombos();
    }
    
public void llenarTabla() {
    DefaultTableModel modelo = (DefaultTableModel) tablaAPU.getModel();
    modelo.setRowCount(0); 
    
    List<Controlador.AsignacionPerfilUsuario> lista = dao.select();
    
    for (Controlador.AsignacionPerfilUsuario asig : lista) {
       
        Object[] fila = {asig.getUsucodigo(), asig.getPercodigo()};
        modelo.addRow(fila);
    }
}

public void cargarCombos() {
    try (Connection conn = Modelo.Conexion.getConnection()) {
        // Cargar Usuarios
        PreparedStatement stmtU = conn.prepareStatement("SELECT Usucodigo, Usunombre FROM usuario");
        ResultSet rsU = stmtU.executeQuery();
        cbxusuario.removeAllItems();
        while (rsU.next()) {
            cbxusuario.addItem(rsU.getInt("Usucodigo") + " - " + rsU.getString("Usunombre"));
        }

        // Cargar Perfiles
        PreparedStatement stmtP = conn.prepareStatement("SELECT Percodigo, Pernombre FROM perfiles");
        ResultSet rsP = stmtP.executeQuery();
        cbxperfil.removeAllItems();
        while (rsP.next()) {
            cbxperfil.addItem(rsP.getInt("Percodigo") + " - " + rsP.getString("Pernombre"));
        }
    } catch (SQLException ex) {
        ex.printStackTrace(System.out);
    }
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxusuario = new javax.swing.JComboBox<>();
        cbxperfil = new javax.swing.JComboBox<>();
        btnregistrar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAPU = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnbuscar = new javax.swing.JButton();
        txtbuscado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("USUARIO:");

        jLabel2.setText("PERFIL");

        cbxusuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxperfil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnlimpiar.setText("Limpiar ");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        tablaAPU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usucodigo", "Percodigo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaAPU);

        jScrollPane2.setViewportView(jScrollPane1);

        jLabel3.setText("BUSCAR POR ID:");

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxperfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btneliminar)
                    .addComponent(btnregistrar)
                    .addComponent(btnlimpiar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbuscado, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnbuscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxperfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnregistrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btneliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnlimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnbuscar)
                    .addComponent(txtbuscado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
                                         
    String idABuscar = txtbuscado.getText().trim();
    if (idABuscar.isEmpty()) {
        llenarTabla();
        return;
    }

    DefaultTableModel modelo = (DefaultTableModel) tablaAPU.getModel();
    modelo.setRowCount(0);
    
    List<Controlador.AsignacionPerfilUsuario> lista = dao.select();
    for (Controlador.AsignacionPerfilUsuario asig : lista) {
        
        if (String.valueOf(asig.getUsucodigo()).equals(idABuscar)) {
            modelo.addRow(new Object[]{asig.getUsucodigo(), asig.getPercodigo()});
        }
    }
    
        
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed

        cbxusuario.setSelectedIndex(0);
        cbxperfil.setSelectedIndex(0);
        txtbuscado.setText("");

        llenarTabla();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
int filaSeleccionada = tablaAPU.getSelectedRow();
    
    if (filaSeleccionada >= 0) {
       
        int idUsu = (int) tablaAPU.getValueAt(filaSeleccionada, 0);
        int idPer = (int) tablaAPU.getValueAt(filaSeleccionada, 1);

        Controlador.AsignacionPerfilUsuario asigAEliminar = new Controlador.AsignacionPerfilUsuario(idUsu, idPer);

        
        if (dao.delete(asigAEliminar) > 0) {
            JOptionPane.showMessageDialog(null, "Asignación eliminada correctamente");
            llenarTabla();
        }
    } else {
        JOptionPane.showMessageDialog(null, "Por favor, selecciona una fila de la tabla primero");
    }
        
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed

        try{
        int idUsu = Integer.parseInt(cbxusuario.getSelectedItem().toString().split(" - ")[0]);
        int idPer = Integer.parseInt(cbxperfil.getSelectedItem().toString().split(" - ")[0]);

    
        Controlador.AsignacionPerfilUsuario nuevaAsig = new Controlador.AsignacionPerfilUsuario(idUsu, idPer);

        
        if (dao.insert(nuevaAsig) > 0) {
            JOptionPane.showMessageDialog(null, "Asignación registrada con éxito");
            llenarTabla(); 
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al registrar: " + e.getMessage());
    }



    }//GEN-LAST:event_btnregistrarActionPerformed



    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenimientoAsignacionPerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenimientoAsignacionPerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenimientoAsignacionPerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenimientoAsignacionPerfilUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenimientoAsignacionPerfilUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JComboBox<String> cbxperfil;
    private javax.swing.JComboBox<String> cbxusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaAPU;
    private javax.swing.JTextField txtbuscado;
    // End of variables declaration//GEN-END:variables
}
